version: '3'
services:
  node-api:
    build: ./node-api
    ports:
      - "3001:3001"
    networks:
      - app-network

  react-app:
    build: ./react-app
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - node-api

networks:
  app-network:
    driver: bridge
